name: Deploy to Render

on:
  push:
    branches:
      - main
      - traffic-lights-fetcher-4166021349994258580

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
